### ISSUE TITLE
Allow adding custom environment variables

### ISSUE THREAD

**Issue by jrauschenbusch** [grafana/tempo-operator#1135]
There is a need for a feature to add extension for `env` and `envFrom` in the TempoStack CRD, to allow mounting sensitive secrets via k8s Secrets. Those secrets could be in turn provided by e.g. External Secrets Operator.

Especially for the use case of adding an external cache, this would make sense as `-config.expand-env=true` is enabled out-of-the-box.

```yaml
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
spec:
  extraConfig:
    tempo:
      cache:
        caches:
          - roles:
              - parquet-footer
              - bloom
              - frontend-search
            redis:
              endpoint: "redis.host"
              db: 0
              tls_enabled: true
              password: "${REDIS_PASSWORD}:-default"
```
