### ISSUE TITLE
Create grafana-operator datasource CR for tempo if grafanaOperator feature gate is set

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo-operator#423]
Create a grafana-operator datasource CR for tempo if grafanaOperator feature gate is set

https://github.com/grafana-operator/grafana-operator/blob/master/docs/docs/datasources.md
```[tasklist]
### Tasks
- [x] Create `grafanaOperator` feature gate [projectconfig_types.go](https://github.com/grafana/tempo-operator/blob/16d885d398c7eec67d8952005337379823a9dac7/apis/config/v1alpha1/projectconfig_types.go#L172), [default config](https://github.com/grafana/tempo-operator/blob/16d885d398c7eec67d8952005337379823a9dac7/config/overlays/community/controller_manager_config.yaml#L32)
- [x] Create `GrafanaDatasource` object ([docs](https://github.com/grafana-operator/grafana-operator/blob/master/docs/docs/datasources.md#plugins))
```

**Comment by ritaCanavarro** [comment]
Hi, I would like to take this. Can you please assign it to me?

**Comment by frzifus** [comment]
@andreasgerstmayr should the datasource point to the gateway if enabled?

**Comment by andreasgerstmayr** [comment]
> @andreasgerstmayr should the datasource point to the gateway if enabled?

Yes. However, iirc currently the gateway is missing some endpoints (like `/ping`) which Grafana requires.

**Comment by ritaCanavarro** [comment]
Hi @andreasgerstmayr,
We can close this Issue and open two new ones as discussed 😄

**Comment by andreasgerstmayr** [comment]
Yep, I've created https://github.com/grafana/tempo-operator/issues/707 for the `GrafanaDatasource` with gateway

**Comment by andreasgerstmayr** [comment]
Completed in #619

**Comment by fliegera** [comment]
Is this really working?
I installed the Operator Version 4 and vreated an instance with the following configMap

```
apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 2c0156f0.integreatly.org
featureGates:
  openshift:
    openshiftRoute: true
    servingCertsService: true
    oAuthProxy:
      defaultEnabled: true
  grafanaOperator: true

```
When I want to create a Tempostack as follows I get the error that the featuregate grafanaOperator should be enabled

```
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: dev-distributed-tracing
  namespace: dev-distributed-tracing
spec:
  observability:
    tracing:
      jaeger_agent_endpoint: 'localhost:6831'
    grafana:
      createDatasource: true      
  resources:
    total:
      limits:
        cpu: 2000m
        memory: 2Gi
  tenants:
    mode: static
  managementState: Managed
  template:
    queryFrontend:
      jaegerQuery:
        ingress:
          type: route
        enabled: true
  storage:
    secret:
      name: distributed-tracing-s3-secret
      type: s3
  storageSize: 1Gi
```

**Comment by andreasgerstmayr** [comment]
> Is this really working? I installed the Operator Version 4 and created an instance with the following configMap
> 
> ```
> apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
> kind: ControllerManagerConfig
> [...]
> featureGates:
>   openshift:
>     openshiftRoute: true
>     servingCertsService: true
>     oAuthProxy:
>       defaultEnabled: true
>   grafanaOperator: true
> ```

Did you edit the ConfigMap of the grafana operator? The `grafanaOperator: true` must be set in the tempo-operator ConfigMap, which looks like this (note the `apiVersion: config.tempo.grafana.com/v1alpha1`):
```
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: config.tempo.grafana.com/v1alpha1
    kind: ProjectConfig
    leaderElection:
      leaderElect: true
      resourceName: 8b886b0f.grafana.com
    [...]
```
