### ISSUE TITLE
Add Enabled field to IngressSpec

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo-operator#503]
For example:
```
jaegerQuery:
  enabled: true
  ingress:
    enabled: true # new field
    type: ingress
```

Pros:
* consistency with other options, which have an `enabled` field for enabling/disabling the component

Cons:
* technically redundant, if the ingress `type` is set --> enable ingress, if it is not set --> disable ingress
