### ISSUE TITLE
Support configuration of TLS in receiver settings 

### ISSUE THREAD

**Issue by frzifus** [grafana/tempo-operator#527]
Support configuring TLS on the distributor.
See: https://grafana.com/docs/tempo/latest/configuration/tls/#receiver-tls

I would like to enable TLS on the OpenTelemetry end to ship traces into tempo. 

Example exporter config:
```yaml
exporters:
  # Export the application tenant traces to a Tempo instance
  otlp/application:
    endpoint: tempo-observatorium-tempostack-distributor:4317
    tls:
      insecure: false
      ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
```

cc @andreasgerstmayr
