### ISSUE TITLE
WriteToFailed in ingester and distributor

### ISSUE THREAD

**Issue by diptripa** [grafana/tempo-operator#570]
Hey guys, started seeing this error after updating the config on tempostack.
`level=warn ts=2023-08-24T06:51:02.952204179Z caller=tcp_transport.go:428 component="memberlist TCPTransport" msg="WriteTo failed" addr=10.36.87.55:7946 err="dial tcp 10.36.87.55:7946: i/o timeout"`

Added this block to the tempostack config post which it started showing.
```
  limits:
    global:
      ingestion:
        maxTracesPerUser: 1000000
  retention:
    global:
      traces: 168h # 7 days
```
