### ISSUE TITLE
Changing replicas for compactor, querier and query-frontend doesn't work

### ISSUE THREAD

**Issue by yaroslavkasatikov** [grafana/tempo-operator#598]
tempo operator: v0.4.0
tempo version: v2.1.1
okd 4.11

I tried to change replication for all components ( want to use 3 pods for each components). Here is my TempoStack CR:
```
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
  namespace: tempo
spec:
  limits:
    global:
      ingestion: {}
      query:
        maxSearchDuration: 0s
  managementState: Managed
  observability:
    metrics: {}
    tracing:
      jaeger_agent_endpoint: localhost:6831
  replicationFactor: 1
  resources:
    total:
      limits:
        cpu: "2"
        memory: 2Gi
  retention:
    global:
      traces: 48h0m0s
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  serviceAccount: tempo-simplest
  storage:
    secret:
      name: minio-test
      type: s3
  storageSize: 1Gi
  template:
    compactor:
      replicas: 3
    distributor:
      replicas: 3
    gateway:
      component: {}
      enabled: false
      ingress:
        route: {}
    ingester:
      replicas: 3
    querier:
      replicas: 3
    queryFrontend:
      component:
        replicas: 3
      jaegerQuery:
        enabled: true
        ingress:
          route: {}
```

So as result, I'm waiting for 3 pods for all components, but only distributer and ingester replicas counts have been applied:
```
[user@yaroslav-new templates]$ oc get deploy
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
tempo-simplest-compactor        1/1     1            1           5m8s
tempo-simplest-distributor      3/3     3            3           5m8s
tempo-simplest-querier          1/1     1            1           5m8s
tempo-simplest-query-frontend   1/1     1            1           5m8s
[user@yaroslav-new templates]$ oc get pod
NAME                                            READY   STATUS      RESTARTS   AGE
tempo-simplest-compactor-7dccbd99d9-dfj6l       1/1     Running     0          5m12s
tempo-simplest-distributor-6578f9c58d-7pg9h     1/1     Running     0          5m11s
tempo-simplest-distributor-6578f9c58d-qfhzh     1/1     Running     0          5m11s
tempo-simplest-distributor-6578f9c58d-w9hqr     1/1     Running     0          5m11s
tempo-simplest-ingester-0                       1/1     Running     0          8m46s
tempo-simplest-ingester-1                       1/1     Running     0          10m
tempo-simplest-ingester-2                       1/1     Running     0          12m
tempo-simplest-querier-7554c957d7-w54r7         1/1     Running     0          5m12s
tempo-simplest-query-frontend-dcc8b67f8-d7bdm   2/2     Running     0          5m11s
```

Target state:
All replicas counts should be applied for all components
