### ISSUE TITLE
Cannot enable gateway while disabling jaeger ui

### ISSUE THREAD

**Issue by philipgough** [grafana/tempo-operator#628]
The following snippet fails for me 
```
      tenants:
        mode: openshift
        authentication:
          - tenantName: application
            tenantId: application
      template:
        gateway:
          enabled: true
        queryFrontend:
          jaegerQuery:
            enabled: false
```
Error: `The TempoStack "tempostack" is invalid: spec.template.gateway.enabled: Invalid value: true: to use the gateway, please enable jaegerQuery
`

Probably misunderstanding something but the use case is to continue to leverage authn/authz at the gateway without the need for jaeger on the query path (I want the route to point at the Loki components/services) in such a case.
