### ISSUE TITLE
Inline TempoComponentSpec struct in spec.template.

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo-operator#715]
Currently the rendered version of a TempoStack looks like this:
```
template:
  compactor:
    replicas: 1
  distributor:
    component:
      replicas: 1
  ingester:
    replicas: 2
  querier:
    replicas: 1
  queryFrontend:
    component:
      replicas: 1
```

Where `replicas` is directly under the component for `compactor`, `ingester` and `querier`, but not for `distributor` and `queryFrontend`.

In the code at https://github.com/grafana/tempo-operator/blob/5a79e619f268dac0fefd6cc394555582b17de520/apis/tempo/v1alpha1/tempostack_types.go#L521-L522 is a link to https://github.com/golang/go/issues/6213, but I don't follow, afaics the following works fine:
```
type TempoDistributorSpec struct {
    TempoComponentSpec `json:",inline"`
}
```
and is already used at another place:
```
type TempoStack struct {
	metav1.TypeMeta   `json:",inline"`
}
```

Is there a corner case I'm missing here? Or did this feature get implemented in the meantime?
