### ISSUE TITLE
Replicas + resources.total.limits

### ISSUE THREAD

**Issue by devoxel** [grafana/tempo-operator#721]
The resource sizing [logic](https://github.com/grafana/tempo-operator/blob/6daca21fa06ea4a13ff0201822e825946471c820/internal/manifests/manifestutils/resources.go#L36) does not take into account the number of replicas assigned.

To demonstrate, here is the following TempoStack definition

```
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
spec:
  images:
    tempo: docker.io/grafana/tempo:x.y.z
    tempoQuery: docker.io/grafana/tempo-query:x.y.z
    tempoGateway: quay.io/observatorium/api
    tempoGatewayOPA: quay.io/observatorium/opa-openshift
  storage:
    secret:
      name: minio-test
      type: s3
  resources:
    total:
      limits:
        memory: 50Gi
        cpu: 10000m
# uncomment and test the difference in output
# template:
#   compactor:
#     replicas: 5
  storageSize: 1Gi
 ```
 
The diff between the version with a comment and without is:

```
<   replicas: 5
---
>   replicas: 1
```

I think this behaviour is not intuitive, and might lead to people over-provisioning their cluster by accident.
