### ISSUE TITLE
Allow resource limits overrides

### ISSUE THREAD

**Issue by mncf9** [grafana/tempo-operator#726]
Currently, Tempo Stack controls how resources are distributed amongst the Tempo deployments. This might lead to the resource wasting. While some of the deployments have overcommitted limits, the other struggle to get more. Just as in my case:
![image](https://github.com/grafana/tempo-operator/assets/155924026/c159a1cd-73e6-465c-8ce5-61e641f87f2d)

You can clearly see that the Ingester does not need such high resources reserved while the Compactor practically gets OOM Killed all the time. Of course I have scaled up to a bigger instance to keep compactor alive, but then I have tons of resources being wasted. 

How about Tempo Stack allowed overriding components limits? E.g like that:
```
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: stack
  namespace: tempons
spec:
  resources:
    total:
      limits:
        memory: 24Gi
        cpu: 1000m
  template:
    compactor:
      resources:
        limits:
          cpu: 500m
          memory: 16Gi
    queryFrontend:
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
```
